### ISSUE TITLE
server error 500 No command specified

### ISSUE THREAD

**Issue by nikhilmone** [docker/kitematic#1245]
While pulling image Fedora, i get this error 

server error
500
No command specified

**Comment by FrenchBen** [comment]
Unfortunately that is the expected behavior, as the Fedora image doesn't seem to provide the command needed for the container to start. 
See: https://hub.docker.com/_/fedora/

You could run it in the console and then see it within kitematic:
`docker -it $(docker-machine config default) run fedora /bin/bash

**Comment by FrenchBen** [comment]
no feedback after a week. closing
