### ISSUE TITLE
Standalone download missing

### ISSUE THREAD

**Issue by rbq** [docker/kitematic#1307]
I tried to get a recent copy of Kitematic but the only option seems to be the Toolbox installer.

* The package is gigantic and includes mostly stuff I don't need
* It requires admin permissions, even if you only want the Kitematic.app
* It unnecessarily installs additional copies of Docker binaries (I'm quite happy with my MacPorts version, thanks)
* Some of the binaries aren't even optional
* It seems hard/impossible to manually extract the Kitematic.app from the pkg
* The Mixpanel opt-out is not actually working

Why is it so hard to get this Application?

**Comment by FrenchBen** [comment]
@rbq You must've missed the release page of this very repo:
https://github.com/docker/kitematic/releases

Click the kitematic.zip of choice and have the Kitematic.app separate from the toolbox. Please be advise that for it to work properly you will need the corresponding virtualbox version installed and additional tools that are shipped with the toolbox. This is precisely why we encourage the download of the Docker Toolbox so that you are setup with the tools that work together.

**Comment by rbq** [comment]
Awesome, thanks!

**Comment by refactorized** [comment]
What could be clearer, is what to do when you already have the docker app for mac or windows, and want kitematic too.  I believe I installed docker from brew - and I think I have everything I need, but the kitematic site now seems to be pushing the docker toolbox - and I thought that the app was the newer better alternative than setting up a virtualbox host.

**Comment by AnimaMundi** [comment]
I'd like to use this with Docker running on Enterprise Windows with Hyper-V, is it possible or does it only work with VirtualBox? VirtualBox and Hyper-V are mutually exclusive.
