### ISSUE TITLE
Support for docker-machine different than default

### ISSUE THREAD

**Issue by fballiano** [docker/kitematic#1324]
Hello everybody, I'm loving Kitematic but as far as I understood (little experience with the whole docker ecosystem) I can't use Kitematic if I'm using dinghy (https://github.com/codekitchen/dinghy) as my docker machine of choice.

would it be possible to add to Kitematic the selection of which docker-machine to use?

**Comment by FrenchBen** [comment]
I'm not too familiar with dinghy, but if you create a VM named default with the virtualbox drivers, based on the dinghy cli, then I don't see why Kitematic wouldn't connect to it.

**Comment by fballiano** [comment]
ok. it's just that at the moment dinghy creates a vm called in a different way and i'd prefer it to keep this behavior so that I can easily switch between dinghy and the default.

**Comment by FrenchBen** [comment]
aside from the NFS sync, I'm missing what Dinghy does that the regular docker cli doesn't already do?

**Comment by fballiano** [comment]
that's mostly it

**Comment by fballiano** [comment]
but it makes a huge difference when you work with really big softwares like Magento

**Comment by elmar-hinz** [comment]
I think this request is still as reasonable as in 2015. Also osxfs in the new docker-for-mac is slow and dangerous. It destroyed my database today.

People do all kind of hacks to get around this buggy design and to be able to use full-blown NFS. Dinghy is only one example.

https://github.com/stephank/docker-for-mac-nfs

So yes, it should be made easy to connect kitematic to a machine of the users choice.

**Comment by FrenchBen** [comment]
@elmar-hinz can you detail how it's dangerous and destroyed your database?

**Comment by elmar-hinz** [comment]
I gonna try. 

For years I used a setup of virtual machines based on Vagrant, VirtualBox and NFS. For a long period I even stored them on USB stick and never suffered a data loss. I also used docker containers inside VirtualBox.

Now I was evaluating Docker-For-Mac with the official MariaDB container. To be able to throw containers away, I stored the DB on the local machine by mounting a directory, to stay on the safe side.

AFAIK Docker-For-Mac mounts by a FUSE variant. Within one day, upon the first crash of the Mac due to an empty battery, I was unable to reconnect the DB. The mounting itself kept woking.

It was an evaluation database, so nothing was lost. 

A single user report doesn't give a statistic. From my point of view it's very surprising that the NFS setup is working for years, while the Docker-For-Mac crashes the DB within 24 hours upon the first occasion.

I also experimented with FUSE ten years ago and it was quite limited compared to NFS.
