### ISSUE TITLE
bug: "no such container 404 no such id".

### ISSUE THREAD

**Issue by evoncken** [docker/kitematic#1334]
Temporary containers created during a "docker build" are normally deleted.
Generated container name (angry_northcutt) was apparently stopped and removed after container build finished, but still displayed in left column. Race condition?

Cannot remove this entry; right panel shows error message:

       no such container
                   404
   no such id: angry_northcutt

Kinematic 0.9.3 on Mac OSX El Capitan 10.11.2

**Comment by FrenchBen** [comment]
It's similar to a Race condition, but with events. The right panel listens for changes but can sometimes fail to properly refresh. You can't delete the container because it no longer exists, Kitematic simply failed to update the left panel.

It's been difficult to track down the cause as it's not 100% repro. 
Thanks for the feedback.
