### ISSUE TITLE
[Feature Proposal] Start containers as soon as Kitematic starts up

### ISSUE THREAD

**Issue by spadin** [docker/kitematic#1397]
It'd be nice if there were a setting to have certain containers start-up automatically as soon as Kitematic starts up. I tend to quit out of Kitematic (and shutdown VM) when I'm not using it. So next time I start it up I have to click on each container and start them individually.

Great work on Kitematic! It's a very helpful app.

**Comment by FrenchBen** [comment]
As an alternative, you can change the pref for Kitematic not to shutdown the VM on close - That's usually what I do, which keeps the VM up and thus all of your containers up and running as well.
Feel free to look through the code and propose it as a feature. :)

Closing this for now due to the low impact of the feature.
