### ISSUE TITLE
On OSX adding a Bridged adapter to VirtualboxIP causes problem

### ISSUE THREAD

**Issue by nodje** [docker/kitematic#1436]
``IP: 192.168.3.155 is not in the cert's list: 10.0.2.15``
It seems that the new address gotten by the Bridged adapter is causing trouble.
I can't start a container via Kinematic anymore

Edit:
also ``docker-machine ls``
gives
``
NAME      ACTIVE   URL          STATE     URL                        SWARM   DOCKER    ERRORS
default   -        virtualbox   Running   tcp://192.168.3.155:2376           Unknown   Unable to query docker version: Get https://192.168.3.155:2376/v1.15/version: x509: certificate is valid for 10.0.2.15, not 192.168.3.155
``
which seems to indicate that the problem doesn't come from Kinematic proper.

**Comment by FrenchBen** [comment]
If docker-machine can't communicate with the VM, then Kitematic wont be able to either - The issue you're seeing is simply due to the new IP and the fact that the certs were made for the previous IP.
You should be able to regen the certs and fix all this:
`docker-machine regenerate-certs default`

**Comment by bcooney** [comment]
Not to hijack this issue, but I am having the same problem as @nodje. When I use `docker-machine regenerate-certs default` as suggested, the certs regenerate fine, but there's now a second error which is preventing me from using Docker:

_This machine has been allocated an IP address, but Docker Machine could not
reach it successfully.

SSH for the machine should still work, but connecting to exposed ports, such as
the Docker daemon port (usually <ip>:2376), may not work properly.

You may need to add the route manually, or use another related workaround.

This could be due to a VPN, proxy, or host file configuration issue.

You also might want to clear any VirtualBox host only interfaces you are not using._

Any advice? Thanks.

**Comment by FrenchBen** [comment]
@bcooney it sounds like some Vbox network issues - If the VM is brand new (aka it can be blown away) then I would do just that via `docker-machine rm default` and re-create one by opening Kitematic

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
