### ISSUE TITLE
When I create ibmdashdb/preview, error

### ISSUE THREAD

**Issue by yanggy2002** [docker/kitematic#1604]
server error 500 when  excute step 6)

4) Restart Kitematic.

5) In the Kitematic GUI, click on "My Repos" in the FILTER BY field.

6) Find the dashDB preview tile and click on the CREATE button.

**Comment by FrenchBen** [comment]
500 usually means that the container failed to create because of a specific issue with what the container needs to start - Since this is a private repo, I can't see the build, but it's not specific to Kitematic, rather what the container needs to start properly.

Try to run it via the command line and see what the difference is.
