### ISSUE TITLE
Codesign verification fails on OS X 10.9.5 and 10.10.5

### ISSUE THREAD

**Issue by apettinen** [docker/kitematic#1647]
### Expected behavior

Codesign verification would pass on all supported OS X versions
### Actual behavior

Codesign verification does not pass on 10.9.5 or 10.10.5 but passes on 10.11.4
##### Running `codesign`

```
codesign --verify --verbose=4 Kitematic\ \(Beta\).app/
--prepared:/path/to/Kitematic (Beta).app/Contents/Frameworks/Electron   Framework.framework/Versions/Current/.
--validated: /path/to/Kitematic (Beta).app/Contents/Frameworks/Electron Framework.framework/Versions/Current/.
Kitematic (Beta).app/: invalid signature (code or signature have been modified)
In subcomponent: /path/to/Kitematic (Beta).app/Contents/Frameworks/Kitematic (Beta) Helper EH.app
```
##### Running `spctl`to mimic Gatekeeper

```
spctl -a -t exec -vv Kitematic\ \(Beta\).app/
Kitematic (Beta).app/: invalid signature (code or signature have been modified)
```
##### Running `codesign`

```
codesign --verify --verbose=4 Kitematic\ \(Beta\).app/
--prepared:/path/to/Kitematic (Beta).app/Contents/Frameworks/Kitematic (Beta) Helper NP.app
--validated:/path/to/Kitematic (Beta).app/Contents/Frameworks/Kitematic (Beta) Helper NP.app
--prepared:/path/to/Kitematic (Beta).app/Contents/Frameworks/Kitematic (Beta) Helper EH.app
--validated:/path/to/Kitematic (Beta).app/Contents/Frameworks/Kitematic (Beta) Helper EH.app
--prepared:/path/to/Kitematic (Beta).app/Contents/Frameworks/Electron Framework.framework/Versions/Current/.
--validated:/path/to/Kitematic (Beta).app/Contents/Frameworks/Electron Framework.framework/Versions/Current/.
--prepared:/path/to/Kitematic (Beta).app/Contents/Frameworks/Kitematic (Beta) Helper.app
--validated:/path/to/Kitematic (Beta).app/Contents/Frameworks/Kitematic (Beta) Helper.app
--prepared:/Users/pettinen/.Trash/Kitematic (Beta).app/Contents/Frameworks/Mantle.framework/Versions/Current/.
--validated:/path/to/Kitematic (Beta).app/Contents/Frameworks/Mantle.framework/Versions/Current/.
--prepared:/path/to/Kitematic (Beta).app/Contents/Frameworks/Squirrel.framework/Versions/Current/.
--validated:/path/to/Kitematic (Beta).app/Contents/Frameworks/Squirrel.framework/Versions/Current/.
--prepared:/path/to/Kitematic (Beta).app/Contents/Frameworks/ReactiveCocoa.framework/Versions/Current/.
--validated:/path/to/Kitematic (Beta).app/Contents/Frameworks/ReactiveCocoa.framework/Versions/Current/.
Kitematic (Beta).app/: valid on disk
Kitematic (Beta).app/: satisfies its Designated Requirement
```
##### Running `spctl`

```
spctl -a -t exec -vv Kitematic\ \(Beta\).app/
Kitematic (Beta).app/: accepted
source=Developer ID
origin=Developer ID Application: Docker Inc (9BNSXJN65R)
```
### Information about the Issue

This is probably related to Apple changing their certificate in mid-February 2016. See https://developer.apple.com/support/certificates/expiration/ for further details.
### Steps to reproduce the behavior
1. Download Kitematic 0.10.2 (or 0.10.1) and extract the app
2. run `codesign --verify --verbose=4 Kitematic (Beta).app` on 10.9.5/10.10.5/10.10.4

**Comment by FrenchBen** [comment]
Thanks for the report - CC @jeffdm

**Comment by urkle** [comment]
I've been looking into this, and the issue here is not the certificate being changed, but rather the application not being signed correctly.    Apple's [documentation](https://developer.apple.com/library/mac/technotes/tn2206/_index.html#//apple_ref/doc/uid/DTS40007919-CH1-TNTAG404) states that you should not be using --deep to codesign, only to verify.

What I use to codesign is my own custom made script that wraps up what XCode would normally do if it were to codesign an application.   This adds the proper codesigning requirements that running codesign bare does not attach.

What I did to get Kitematic to be signed correctly and validate on OS X 10.9/1.10 as well as 10.11 is I removed ALL of the _CodeSigning folders (as there were some extra files added in them that should not be there, probably from the --deep) and then ran my script on the app to code-sign it.

https://gist.github.com/urkle/93bddd0aaa7d5e692f0ec03df377f4d0

**NOTE** this script has been used for codesigning LOTS of released applications (Largely game ports that I do for Humble Bundle) and thus is battle tested.

**Comment by FrenchBen** [comment]
Thanks for sharing @urkle I'll review it and will update our signing process to use that instead
