### ISSUE TITLE
Cannot run npm install with latest master branch version

### ISSUE THREAD

**Issue by alexandrev** [docker/kitematic#1719]
### Expected behavior

Sucessfully execution of npm install

### Actual behavior

```
PS D:\Projects\GitHub> cd .\kitematic\
PS D:\Projects\GitHub\kitematic> npm install
npm ERR! Windows_NT 10.0.14352
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3
npm ERR! code EBADPLATFORM

npm ERR! notsup Not compatible with your operating system or architecture: grunt-electron-installer-redhat@0.3.0
npm ERR! notsup Valid OS:    darwin,linux
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
```

### Steps to reproduce the behavior

  1. npm install

**Comment by bdharris08** [comment]
'grunt-electron-installer-debian' and 'grunt-electron-installer-redhat' will not work with windows, so you can just remove those lines from the devDependencies section of your package.json. 

Looks like those were added in the Ubuntu/Debian install merge - #1677 so that the gruntfile can use them.

Some googling reveals three ways to fix:

1. move the two packages to optional dependencies section in package.json (this already happens in the docker-modem and JSONStream packages - they optionally depend on 'chokidar/fsevents'
2. use a postinstall script and node 'os' to install the package based on the os type (however node would return 'linux' for both redhat and debian
3. expect new windows developers to simply delete the -debian and -redhat packages from package.json.

Any thoughts? 

I submitted a PR #1723 - with option 1, but need a quick install and build test on debian and redhat to verify the gruntfile will still work.

**Comment by FrenchBen** [comment]
@alexandrev sorry for breaking it, should've double-checked on windows - I'll fix it tomorrow

**Comment by FrenchBen** [comment]
I believe most of these to be fixed in the latest Docker for Mac/Windows+Kitematic.
