### ISSUE TITLE
Error: getaddrinfo ENOTFOUND docker.local docker.local:2375

### ISSUE THREAD

**Issue by sandipsclarion** [docker/kitematic#1804]
### Expected behavior
I have installed Dcoker toolbox on windows 8. Once the installation done i run docker terminal.
all the process done in terminal.
then i opened kitematic, but it showing me error  "Error: getaddrinfo ENOTFOUND docker.local docker.local:2375"
it should open the ui to manage docker containers
### Actual behavior
but it showing me error  "Error: getaddrinfo ENOTFOUND docker.local docker.local:2375"

### Information about the Issue
![screenshot 1467699860](https://cloud.githubusercontent.com/assets/16461960/16575717/005ec40a-42a8-11e6-9cdb-f3ae73a65657.jpg)

### Steps to reproduce the behavior

  1. ...install docker
  2. ...run docker
  3....once the docker created IP
  4....run kitematic

**Comment by rusmo** [comment]
+1 - I've been seeing this issue for the last two weeks on both Win 8.1 64-bit and Win 10 64-bit using the docker toolbox installer v1.11.2.

**Comment by FrenchBen** [comment]
Clicking on `Use Virtualbox` is the proper option. 
With the release of Docker for Mac and Docker for Windows, Kitematic is biased towards those setup, instead of the old Virtualbox.

**Comment by sandipsclarion** [comment]
yes it's works

**Comment by FrenchBen** [comment]
Feel free to get the current public beta of Docker for Mac and Docker for Windows:
https://www.docker.com/products/docker

**Comment by fjossandon** [comment]
@FrenchBen `Feel free to get the current public beta of Docker for Mac and Docker for Windows:` Tried to do that but I have Windows 10 x64 home, and the installer says that it won't run in home version. But I cannot upgrade to Pro because Windows won't let me, it says it cannnot do it for my edition (maybe because it was upgraded from Win8.1?) So I'm obligated to use Docker Toolbox.

Will Docker support Home in the future? Or I will have to be limited to Toolbox? Are there many downsides to use Toolbox instead of Docker? I could not find a comparative table between both that will tell me if I'm missing something critical for not being able to install Docker for Windows.

**Comment by FrenchBen** [comment]
I upgraded my `Home` edition to `Pro` - just need to purchase it from the Windows Store for $99.
The integration of Docker for Windows is seamless, compared to some of the issues people have found with Virtualbox

**Comment by vdillon** [comment]
I seeing this issue using Docker for Windows 1.12.0-rc4-beta19 (build 5465) on Windows 10 Pro x64

**Comment by FrenchBen** [comment]
There's a bug that is currently being worked on:
https://github.com/docker/kitematic/issues/1836

**Comment by rezonant** [comment]
Docker supports Hyper-V in addition to VirtualBox, and for those using Hyper-V for other reasons, using a different hypervisor is not an option.

This bug is due to a recent change in Docker, you can work around the issue by adding an entry to your hosts file (%windir%\drivers\etc\hosts) pointing docker.local to your loop back (127.0.0.1):

`127.0.0.1 localhost`

This should work regardless of your hypervisor.

**Comment by vdillon** [comment]
I edited hosts in %windir%\system32\drivers\etc\hosts and added the line:

`127.0.0.1   docker.local`

Now Kitematic opens w/o the error.

I'm not sure if the next problem I encounter is related.  When I try to 'create' the hello-world-nginx container I get  the error:

> Network timed out while trying to connect to https://index.docker.io/v1/repositories/kitematic/hello-world-nginx/images. You may want to check your internet connection or if you are behind a proxy.

I'm not running behind a proxy.

**Comment by ahoehma** [comment]
Same for me ... I'm using "1.12.0-rc4-beta20".

**Comment by FrenchBen** [comment]
@vdillon thanks for the quick patch, but this isn't the proper fix. 

The pre-release has been created and can be downloaded to verify that it's working as expected:
https://github.com/docker/kitematic/releases/tag/v0.12.1

**Comment by Kylvan** [comment]
Link not available and i got the same issue.

What should i do ?

I'm on W7 x64

**Comment by mtrevor** [comment]
Problem persists in the stable release of Docker for Windows, requiring the manual edit of hosts to work.

Why has this issue been closed when it's very blatantly still active?

**Comment by FrenchBen** [comment]
@Kylvan @mtrevor Latest release is available here:
https://github.com/docker/kitematic/releases/tag/v0.12.0

Can you please give it a try?

**Comment by pepe57** [comment]
I had the same problem! 
loaded and installed : https://github.com/docker/kitematic/releases/tag/v0.12.0

All seems ok

**Comment by smolinari** [comment]
I just updated to (from Docker 1.12 RC 2) and am running Docker 1.12.1 stable and have Win 10 Pro with Hyper-V and got this error. The 

`127.0.0.1 docker.local` 

entry in the `hosts` file fixed it. Thanks for the tip. 

I have to ask, reading @pepe57 's post above. Doesn't Kitematic also get updated automatically, when I update Dock for Windows? 

Scott

**Comment by FrenchBen** [comment]
@smolinari unfortunately the releases are separated right now. There's a few patches in the pipeline and we'll update Kitematic. 

Thanks

**Comment by smolinari** [comment]
@FrenchBen - Are there plans to include it in the future? 

Scott

**Comment by FrenchBen** [comment]
It's currently being discussed internally  :)
