### ISSUE TITLE
Allow to customize the Virtualbox VM name

### ISSUE THREAD

**Issue by dluc** [docker/kitematic#1886]
### Expected behavior
Given that Virtualbox is installed
When I choose to use Virtualbox
Then Kitematic should use a default name like "Kitematic" for the VM
Or prompt me for the actual name

Given that I chose to use a Virtualbox image
When I rename the Virtualbox image (e.g. I don't like "default")
Then Kitematic should be smart enough to find it (e.g. using the underlying VM id)
Or prompt for which VM to use

### Actual behavior
Given that Virtualbox is installed
When I choose to use Virtualbox
Then Kitematic creates a VM named "default" (which is not very helpful)

Given that I chose to use a Virtualbox image
When I rename the Virtualbox image (e.g. I don't like "default")
Then Kitematic creates another "default" VM

### Information about the Issue
Platform: OSX (10.11)

### Steps to reproduce the behavior

  1. Instal VirtualBox
  2. Launch Kitematic
  3. Use Virtualbox -> a new VM is created
  4. Stop Kitematic
  5. Rename the VM from VirtualBox UI
  6. Launch Kitematic
  7. Use Virtualbox -> a new VM is created again

**Comment by FrenchBen** [comment]
Aside from personal preference on the name, the VM created should be something somewhat hidden to the user. 
Essentially you can have all other VM, but the default is Kitematic related. 

Feel free to provide a PR that allows one to set a name within the preference panel:
Relative info of where the machine name is picked:
https://github.com/docker/kitematic/blob/master/src/utils/DockerMachineUtil.js#L17

**Comment by dluc** [comment]
Hi Ben, for users not using VB other than Kitematic it's not an issue, however many developers (I think) use VB for other things too, so they might have multiple VMs already in place. In this scenario, when you launch VB and see a "default" VM, it's not straightforward to guess that that is the Kinematic VM.
Thanks for the pointer, I'll see if that's a reasonably quick change.

**Comment by FrenchBen** [comment]
@dluc Closing this in favor of: https://github.com/docker/kitematic/issues/231

**Comment by STaRDoGG** [comment]
I just installed Docker Toolbox in Win 10 (trying to use Docker For Windows with Hyper-V causes my entire computer to BSOD. I have to keep Hyper-V disabled to boot back into windows) and then I fired up VBox, noticed the vm with the name "default" and immediately hated that undescriptive name :P and renamed it to "Docker"; well, all Hell broke loose ...

Obviously with the rename Docker/Kite couldn't find it, renamed it back, still couldn't use it. Completely uninstalled DT and all folders related to docker that I could find on my system, as well as all reg keys related to docker; reinstalled DT, minus Vbox since it was already installed. Fire up Kitematic and now all I get is this error:

> Command failed: C:\Program Files\Docker Toolbox\docker-machine.exe -D create -d virtualbox --virtualbox-memory 2048 default,Docker Machine Version: 0.16.1, build cce350d7,Found binary path at C:\Program Files\Docker Toolbox\docker-machine.exe,Launching plugin server for driver virtualbox,Plugin server listening at address 127.0.0.1:50243,() Calling .GetVersion,Using API Version 1,() Calling .SetConfigRaw,() Calling .GetMachineName,(flag-lookup) Calling .GetMachineName,(flag-lookup) Calling .DriverName,(flag-lookup) Calling .GetCreateFlags,Found binary path at C:\Program Files\Docker Toolbox\docker-machine.exe,Launching plugin server for driver virtualbox,Plugin server listening at address 127.0.0.1:50245,() Calling .GetVersion,Using API Version 1,() Calling .SetConfigRaw,() Calling .GetMachineName,(default) Calling .GetMachineName,(default) Calling .DriverName,(default) Calling .GetCreateFlags,(default) Calling .SetConfigFromFlags,Reading certificate data from C:\Users\Olympus Cloud\.docker\machine\certs\ca.pem,Decoding PEM data...,Parsing certificate...,Reading certificate data from C:\Users\Olympus Cloud\.docker\machine\certs\cert.pem,Decoding PEM data...,Parsing certificate...,(default) Calling .PreCreateCheck,(default) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --version,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | 5.2.24r128163,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },(default) DBG | Hyper-V is not installed.,Error with pre-create check: "This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory",open C:\Users\Olympus Cloud\.docker\machine\machines\default\default\Logs\VBox.log: The system cannot find the path specified.,notifying bugsnag: [Error with pre-create check: "This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory"],

Always the same error, whether I click the Reset button, the Retry Setup button, or the Delete VM and Retry Setup button. I'm stuck here at the moment. I should mention I'm a total noob at this point, when it comes to Docker.

Any ideas?

P.S. I second the motion to allow renaming the VM, or at least give it's default name something more descriptive.
