### ISSUE TITLE
IBM dashDB Local download link not working

### ISSUE THREAD

**Issue by nayakajith** [docker/kitematic#1961]
### Actual behavior
Following error message is listed
Tag latest not found in repository docker.io/dashdb/local
### Information about the Issue
Download link for IBM dashDB Local is not working 
### Steps to reproduce the behavior
  1. ... Search for dashDB docker image
  2. ...Click Create for dashDB local in the search result for repositories
![dashdb_error](https://cloud.githubusercontent.com/assets/21539146/18161273/e3fb63de-704e-11e6-9cd9-53830a236169.png)

Refer screen shot for error message

**Comment by Fahrradflucht** [comment]
Please read the instructions given on https://hub.docker.com/r/dashdb/local/.

This image doesn't provide any public tags you have to register with IBM.

**Comment by FrenchBen** [comment]
@Fahrradflucht thanks for the input - the difficutly for Kitematic to handle the above, is that each image has a very specific set of instructions/conditions which Kitematic cannot handle. 
We'd almost need to have a config entry to declare what the image depends on, so that Kitematic could handle the above errors.

**Comment by Fahrradflucht** [comment]
@FrenchBen I mean not that dashdb's special case could get handled I mean the fact that it has know tags. Isn't that the reason why it technically fails?
