### ISSUE TITLE
Containers have Alzheimer

### ISSUE THREAD

**Issue by FatCyclone** [docker/kitematic#1991]
Hi there,

Try to find out if it's the actual behavior or not.
I've actually made some research but nothing concrete.

### Expected behavior
Set settings, such as ports, or container name should not reset my container.

### Actual behavior
My container resets every time I set some settings.

### Information about the Issue
I'm on Mac OS X, but same thing on Windows 10.
Kitematic 0.12.0
VM is on VirtualBox
Latest Boot2Docker

### Steps to reproduce the behavior

  1. Get a container
  2. Install some packages.
  3. Set ports.
  4. Profit of grandma's Alzheimer.

**Comment by FrenchBen** [comment]
The problem is that you're thinking of containers as a VM, which they're not. Making changes to a container and expecting a different output after you redeployment of the container (via the original image) will  never work. 

Containers cannot be modified on the go, which means that they are always deleted and re-created.
