### ISSUE TITLE
"Exec" in windowsservercore container is not working

### ISSUE THREAD

**Issue by artisticcheese** [docker/kitematic#2166]
### Expected behavior
Supposed to open cmd.exe

### Actual behavior
Opens powershell window for a little bit and then close

### Information about the Issue
When I press "Exec" button on running WindowsServerCore container I expected it to attach to container and start command processor or powershell but instead briefly window is shown and closed in attachment

### Steps to reproduce the behavior

  1. Start windowscore container
2. Press "Exec button"
![image](https://cloud.githubusercontent.com/assets/13176884/20863137/3a3bbac4-b987-11e6-8008-66e9afb49a43.png)

**Comment by FrenchBen** [comment]
What version of powershell are you running and where is it located? The error seems to reflect a missing executable or a different path.

**Comment by artisticcheese** [comment]
Standard location

```

Name                           Value                                                                                                                                                                                
----                           -----                                                                                                                                                                                
PSVersion                      5.1.14393.206                                                                                                                                                                        
PSEdition                      Desktop                                                                                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                              
BuildVersion                   10.0.14393.206                                                                                                                                                                       
CLRVersion                     4.0.30319.42000                                                                                                                                                                      
WSManStackVersion              3.0                                                                                                                                                                                  
PSRemotingProtocolVersion      2.3                                                                                                                                                                                  
SerializationVersion           1.1.0.1      
```

**Comment by FrenchBen** [comment]
@artisticcheese can you provide that path, so that I can compare it to what we are looking for?

**Comment by artisticcheese** [comment]
Default location of
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe

**Comment by artisticcheese** [comment]
It's actually in title bar as you can see of that window.

**Comment by FrenchBen** [comment]
@artisticcheese And you confirmed it actually exists at that location? The title bar showed the exe you try to execute, which may not live at that location.

**Comment by artisticcheese** [comment]
I might be misunderstand what that "exec" button supposed to do. I assumed it will provide me powershell console inside "container", is it correct? So I launch powershell.exe on my host (via that path which is default location) and it will in turn connect to powershell.exe on that specific container I was targeting. Am I  misunderstaing something?

**Comment by FrenchBen** [comment]
The exec button does the same thing as `docker exec -it ...` - I now realize that you're running Windows Containers, and thus it dies due to the fact that Kitematic only knows to pass `sh` as the shell type. 
When you do `docker exec ...` to exec into a container from the CLI, what do you pass?

**Comment by artisticcheese** [comment]
I don't do "docker exec" at all. I do Enter-Pssession to remote into container. So is feature "Exec" from Kitematic is supposed to be working on Windows containers?

**Comment by FrenchBen** [comment]
@artisticcheese Can you try to use `docker exec` to see how it works and behaves?

**Comment by artisticcheese** [comment]
Docker exec as well as Enter-PSSession work just fine to container. Based on screenshot it tries to launch SSH or something even though Container is Windows.  Example of enter-pssession is below

```
PS C:\Users\admin> Invoke-ContainerImage -ImageIdOrName microsoft/iis -Detach
PS C:\Users\admin> Get-Container

ID                   Image           Command              Created                Status               Names
--                   -----           -------              -------                ------               -----
e82e492e528376539... microsoft/iis   C:\ServiceMonitor... 12/12/2016 6:54:21 PM  Up 17 seconds        romantic_kowalevski
fa6c811cee92ba423... microsoft/iis   C:\ServiceMonitor... 12/9/2016 8:58:11 PM   Exited (214748364... iis


PS C:\Users\admin> Enter-PSSession -ContainerId (get-container romantic_kowalevski).ID
[e82e492e5283...]: PS C:\Users\ContainerUser\Documents> whoami
user manager\containeruser
[e82e492e5283...]: PS C:\Users\ContainerUser\Documents>
```

**Comment by twocs** [comment]
Could it be that even when we have switched Docker to use Windows containers, and Docker can no longer open Linux containers, the Exec button in Kitematic is still wired to launch sh?

Here is the error when I run a command like Kitematic might be attempting. 
> PS C:\Program Files\Docker\Docker> docker run -it d9bccb9d4cac sh
> C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container 9962ecd27ce7313bd79783b69f51084e6d0abed92650d562cde8f1c01a5a2c35 encountered an error during CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2) extra info: {"ApplicationName":"","CommandLine":"ps","User":"","WorkingDirectory":"C:\\","Environment":{},"EmulateConsole":true,"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":false,"ConsoleSize":[50,120]}.

When I run this command, it works fine:
> PS C:\Program Files\Docker\Docker> docker run -it d9bccb9d4cac

To work around this problem, it appears that we can set "SHELL" in Kitematic for the container: Settings > Advanced > Environment Variables. Once I set SHELL to "cmd.exe" or "powershell.exe", the Exec button now works just fine.

I would suggest that because the system tray application for Docker has a menu item "Switch to Windows containers...", Kitematic must become aware that when Docker is in Windows containers mode, containers are simply not going to accept 'sh' and must be Windows containers. 

My thought on how to fix these issues surrounding the Exec button: I'd suggest that the SHELL environment Variable is always visible. In other words, Environment Variables should by default list the key: "SHELL" that indicates the value "/bin/sh" (currently the default). This is apparently how Kitematic is dealing with the shell issue anyway, but because it's hidden, it's been a little difficult to really understand how to deal with the problem. This way, users get the default shell but can understand how to change to the shell they want.

**Comment by FrenchBen** [comment]
@twocs I like the idea, as it's something we considered in the past- One of the issue is when a different shell is in use within the image, then which one is 'correct'?
Also that means that we're now injecting special env vars within the container, which may not be the desired effect for most users. 

Having Kitematic detect when a user switched to windows containers has been on our list of things to detect, but isn't as straight forward as one would hope. 

Thank you for the input and keep the ideas coming. Really happy to see some constructive criticism come through :)
