### ISSUE TITLE
Get https://registry-1.docker.io/v1/repositories/library/rabbitmq/tags/latest: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by mateodelnorte** [docker/kitematic#2219]
### Expected behavior
pull down a docker container
### Actual behavior
Get https://registry-1.docker.io/v1/repositories/library/rabbitmq/tags/latest: x509: certificate signed by unknown authority
### Information about the Issue
Get https://registry-1.docker.io/v1/repositories/library/rabbitmq/tags/latest: x509: certificate signed by unknown authority

### Steps to reproduce the behavior

  1. docker-machine start
  2. load kitematic from Docker Toolbox on Windows 7 in a corporate firewalled environment. 
  3. try to download any container
  4. get above error

### Resolution

kitematic needs an option for ssl-strict = false and to use an http version of the registry

**Comment by ajlanghorn** [comment]
I don't know if that _is_ a resolution; more that it's a workaround for your specific use case. `registry-1.docker.io` is signed by a certificate issued by RapidSSL, who are in turn signed by GeoTrust. The GeoTrust root CA is installed, usually by default, so I wonder whether or not your connections to the outside world are being mitm'd, and whatever under the hood that Kitematic uses to make a connection is realising this, and refusing to connect since the certificate presented back to Kitematic is different to the one that actually should be presented.

A better workaround, assuming the above, would be to get whatever egress proxy sits between you and the outside world to accept and properly pass back the certificate issued to `registry-1.docker.io`.

An option to disable SSL verification seems nasty to me, since it encourages bad behaviours and allows for excuses to thrive. Offering a HTTP version of the registry seems like a regression: the web is moving more and more toward accepting HTTPS by default. Kitematic shouldn't really introduce a regression unless there's a very valid and popular need to do so, which I don't think there is here.

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

**Comment by mateodelnorte** [comment]
Yes, I'm behind a corporate firewall. But, no there is no prescribed proxy settings for users here. 

@ajlanghorn I agree it's not the perfect solution for a perfect world, but in reality there are thousands of developers stuck behind corporate firewalls where their IT departments have not property configured their network or firewall settings. As a result, they face the problems I'm facing and fixing network appliance settings, for instance, in a 200,000 person organization is a political problem far harder fought than just setting an environment variable to `ssl-strict=false`.

**Comment by mateodelnorte** [comment]
Frankly, I think this project should favor flexibility for the purpose of fueling adoption. But that's just my opinion, and as it stands and for the reasons above, I am having difficulty setting inroads for it at my very large organization.

**Comment by FrenchBen** [comment]
@mateodelnorte Unfortunately corp firewalls have been pretty difficult to fix with Virtualbox - The latest Docker for Mac and Windows do alleviate this pain. 
I see that you're on Windows 7 which is unfortunately not supported at the moment. 

The issue is the complexity of the corp firewall settings, which involve a bit more than a simple 'flick' of a setting in kitematic. As you can see by the steps described in the wiki, some changes are within the VM on top of Kitematic being ran from the CLI to pickup the firewall details.

**Comment by mateodelnorte** [comment]
I'm not following. If you're saying I should set up a proxy for my corporate firewall, as described here https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes, I mentioned my org doesn't use one. To your point, *because* corp firewall settings are more difficult to navigate than flicking a switch in Kitematic, that's exactly why Kitematic should have a setting allowing it to be lenient in this case. 

npm allows exactly this: https://docs.npmjs.com/misc/config#strict-ssl

I guess what I'm pointing out here is that by electing to not offer an option to skip ssl validation, you're essentially saying that Kitematic only works within organizations that share Docker's security mentality. And, you're not providing a road map for improvement to those that currently don't. Something to keep in mind is that some organizations are incredibly large and changes start within them in small groups working to improve the larger structure.

**Comment by FrenchBen** [comment]
@mateodelnorte it's a lot more complex than just kitematic - Kitematic is only an interface that talks to Docker. 
This means that if you can't do `docker pull  .... ` via the command line, Kitematic isn't going to magically solve this. Since you're running Docker Toolbox, I would encourage you to read:
https://docs.docker.com/docker-for-mac/docker-toolbox/

The wiki doesn't say to setup a proxy, but mentions that the 'firewall' you mention is more than that, it's really a corp proxy that changes how SSL is handled, as @ajlanghorn your connections to the outside world are being mitm'd. What I mean by this is that instead of doing:
you < ---- > Google
it does:
you < ---- > Corp Proxy < --- > Google (corp proxy is what you call the 'firewall')
some ref on the difference: https://www.quora.com/What-is-the-difference-between-a-firewall-and-a-proxy

What the wiki suggests is to obtain the proxy information as seen above, and simply add them to the VM so that it can talk to the outside world properly.
