### ISSUE TITLE
Kitematic doesnt work behind corporate proxy

### ISSUE THREAD

**Issue by mikedevita** [docker/kitematic#2492]
### Expected behavior
Kitematic app should interpret OS level proxy settings or environment variables HTTP_PROXY, HTTPS_PROXY and work behind a proxy, or the UI should provide a config setting to provide proxy settings.

### Actual behavior
Doesn't seem to be working as connections are refused and traffic seems to be routing straight to the endpoints and not through the proxy first.

### Information about the Issue
Build 0.13.0, environment variables are set, and proxy pac file is retrievable.

```
HTTP_PROXY=http://user:pass@proxy:80
HTTPS_PROXY=http://user:pass@proxy:80
```

### Steps to reproduce the behavior
download kitematic, and when trying to sign in to docker hub (the very first screen you come to) it just says connection refused. Additionally clicking skip, you cant pull up or login to the hub.

![screen shot 2017-03-22 at 8 25 39 am](https://cloud.githubusercontent.com/assets/2991640/24205726/6d148cbc-0ed9-11e7-8d01-548aaee9c145.png)
![screen shot 2017-03-22 at 8 27 34 am](https://cloud.githubusercontent.com/assets/2991640/24205730/729ef348-0ed9-11e7-8f46-add91d8adb17.png)

**Comment by mikedevita** [comment]
this seems to actually have fixed its-self, after installing the docker toolbox, and setting the proxy settings in the docker preferences menu I'm able to login to the hub and pull down images.

**Comment by FrenchBen** [comment]
As long as you have the `Use system proxy` turned on it should work properly

**Comment by Malouke** [comment]
Hi maybe that remarque it to late but i sware good it s not cleare aboot docker toolboxe on windows 7 I REAPTE WINDOWS 7 no good documentation are added to clarify how we can configure the proxy with virtualbox behin corporate proxy 
Ok we have to add the environment variable http proxy and https proxy and no proxy (no cleare because the ip adresse provide in nat network should conflict or not the local ip) 
Help use with taking care about configuration windows7 
EXPLAIN US HOW we can resolve confkict
How we can use docker compse correctly inside cmd our instead cygwin or powershell or minwin ....
How we resolve tls problem even with authentication 
We can t change os from windows 7 to 10 
THANKS FOR ADVANCE TO BE CLEAR
