### ISSUE TITLE
Containers does not appear after creation in My images Tab

### ISSUE THREAD

**Issue by anton-arsentyev** [docker/kitematic#2609]
### Expected behavior

1.  Open Kinematic My Images Tab
2.  Create in console new image
3.  New image appear in list 

### Actual behavior

1.  Open Kinematic My Images Tab
2.  Create in console new image
3.  New image does not appear in list 

New image appear only after relaunch

Maybe some refresh button should be there)

**Comment by mhelmetag** [comment]
Basically the issue is that creating an image from the command line doesn't dispatch [this action](https://github.com/mhelmetag/kitematic/blob/master/src/stores/ImageStore.js#L32). I'm not exactly sure why. Working on that. However, It's interesting to note that pulling an image from the command line does dispatch this action.

In other news, there technically is a refresh button. Clicking the "My Images" tab will reload the image list. Not the greatest UX though.

**Comment by FrenchBen** [comment]
@mhelmetag thanks for debugging this - It seems to be related to the events dispatched where a build doesn't trigger anything, but a pull would
