### ISSUE TITLE
Default framework images such as rails, django don't work with Kitematic.

### ISSUE THREAD

**Issue by marcinwyszynski** [docker/kitematic#285]
I'm trying to run the official Rails image and the container immediately shuts down with "Switch to inspect mode" in logs. No further logs are available. The same is happening with the official Ubuntu image, consistently on two different OS X machines.

**Comment by jeffdm** [comment]
Thanks for the issue! Sorry you hit a dead end trying to run the official Rails image with Kitematic.

From what I understand, the official rails image is meant to be used as a base image for your own Dockerfiles. It's page on DockerHub might help: https://registry.hub.docker.com/_/rails/

 In this case running it in Kitematic won't work since it effectively runs nothing.

**Comment by marcinwyszynski** [comment]
I see, thanks! That would not explain the same thing for the Ubuntu image though, no?

**Comment by Elesant** [comment]
Hi @marcinwyszynski, Ubuntu image is a base OS image which is used in other images, but doesn't technically "run" as a prolonged process.

**Comment by rraheja** [comment]
Are there any official OS images that are not only intended as base images but actually "run" as prolonged processes? I tried Ubuntu and CentOS and both stay stopped in the UI (and no process shown using docker ps).

**Comment by shooding** [comment]
Good to know! Base image won't start! Noted!

**Comment by brancusi** [comment]
Same issue here with rails.

**Comment by FrenchBen** [comment]
Closing this issue due to lack of update/activity - Feel free to re-open if appropriate.
