### ISSUE TITLE
redis - HTTP 401

### ISSUE THREAD

**Issue by rotshtein** [docker/kitematic#2863]
### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by FrenchBen** [comment]
Please make sure that you've validated your account prior to pulling an image; this can be done by doing the following:
* Login to cloud.docker.com
* Click on `Account Settings` 
* Check and verify that your primary email has been verified

Additionally, please try try logging into Kitematic with your username instead of email address and see if that fixes your issue.
