### ISSUE TITLE
UI in windows is failing to validate a valid email on "Connect to Docker Hub" screen

### ISSUE THREAD

**Issue by jcollum-cambia** [docker/kitematic#2886]
### Expected behavior

valid email doesn't show error

### Actual behavior

![screenshot](https://user-images.githubusercontent.com/29718037/28681179-70e10fd6-72ad-11e7-9eb8-d6de591722cc.png)

### Information about the Issue

$ docker-machine.exe --version
docker-machine.exe version 0.12.2, build 9371605

Does that help track down the Kitematic version? I don't see any other way to get it, there isn't an about screen that I can find. I installed it a few minutes ago. 

### Steps to reproduce the behavior

should be clear from screenshot

**Comment by FrenchBen** [comment]
This was fixed in the latest releases of Kitematic, which doesn't auto-update. 
Try the latest build from github and let me know if that fixes it. 

FYI, there's currently an issue where some containers cannot be pulled if you use your email to sign-in. I would recommend using your DockerID to prevent this from happening.
