### ISSUE TITLE
kitematic error "self signed certificate in certificate chain"

### ISSUE THREAD

**Issue by saurabhsingh878** [docker/kitematic#3209]
# Information about the Issue
we are run kitematic but showing this error "self signed certificate in certificate chain"

**please provide solution step by step because I am beginner for using docker**

![kitematic](https://user-images.githubusercontent.com/30536242/31963660-19c8dcb6-b91f-11e7-876e-92fe90a280e5.jpg)

**Comment by tmli3b3rm4n** [comment]
same

**Comment by FrenchBen** [comment]
@saurabhsingh878 and @tmli3b3rm4n Can you provide the steps you used to get there?
Is there a custom repo in place? What's your setup? Toolbox? Docker for Mac?

**Comment by saurabhsingh878** [comment]
we are open kitematic and showing this error.
Docker and kitematic all setting default.

toolbox product - 17.07.0-ce
using Docker for Windows

**Comment by FrenchBen** [comment]
what happens when you do `docker pull hello-world` from the CLI?

**Comment by saurabhsingh878** [comment]
when run **docker pull hello-word** from the CLI

Result- 

![image](https://user-images.githubusercontent.com/30536242/32154531-574f3198-bd57-11e7-86a8-498d23d4b95e.png)

**Comment by FrenchBen** [comment]
Are you behind a firewall or VPN? 
See our wiki for possible solutions:
https://github.com/docker/kitematic/wiki/Common-Proxy-Issues-&-Fixes

**Comment by saurabhsingh878** [comment]
we are not using any proxy. how to set proxy.

**Comment by NaifousBS** [comment]
+1 same issue

**Comment by Ubel** [comment]
+1 Same issue. And we don't use proxy.

**Comment by yongwhan2** [comment]
Kitematic can not communicate server using SSL. It cause by SSL proxy like next firewall or SSL decoder.
Please check SSL communication.

**Comment by dhananjaykumar880** [comment]
+1 same issue

**Comment by livingstonep** [comment]
same issue here

**Comment by dclar43** [comment]
Setup: Using Docker for Windows on Windows 10.  

@FrenchBen In my case, and I'm sure many others', this isn't a case of a proxy. I'm simply behind a corporate firewall that does deep packet inspection which causes this error. There is no proxy to go around this as that would defeat the firewall's purpose.  
  
Most if not all other applications correctly reference Windows' certificate store which has the required certificate imported.  That includes Docker for Windows(can pull/push/search etc.). I'm not sure what exactly kitematic is doing differently here :\  
  
Any help would be appreciated.

**Comment by olexiy** [comment]
Same problem as dclar43 - please respond.

**Comment by punix81** [comment]
is the problem fixed ??

**Comment by dracorp** [comment]
Same problem on macos, Kinemematic 0.17.7. In my company we have decrypted network traffic for almost all https connection. The solution to the problem for an application is to inject the CA root at proper place or change configuration for the application.
But for Kinematic I don't know the proper place where to inject the certificate. Kinematic does not use system or user key bundle.

**Comment by dracorp** [comment]
@FrenchBen 
Can you open this issue and "fix" it?
For me the optional option would be add a path to own certificate or  add an option to ignore certificate chain.

**Comment by dclar43** [comment]
@dracorp In the mean time check out Portainer and see if it meets your needs.

**Comment by brunowcordeiro** [comment]
We are experiencing a problem to use the Kitematic docker behind a transparent proxy service.
Our development area uses the Windows environment with Docker to simulate some projects and each workstation has a CA that will be used to encrypt and decrypt web traffic automatically. But when it runs Kitematic it presents the following error: "self signed certificate in certificate chain".
The docker package in question used on the workstations comes from the following source: https://docs.docker.com/v17.12/toolbox/toolbox_install_windows/

Some workarounds have already been performed to run the docker in VM VirtualBox:

mkdir / var / lib / boot2docker / certs
scp bruno@172.27.3.73: /home/bruno/certs_pfsense/CA-SQUID.pem/ var / lib / boot2docker / certs
touch /var/lib/boot2docker/bootlocal.sh && chmod + x /var/lib/boot2docker/bootlocal.sh
vi /var/lib/boot2docker/bootlocal.sh
#! / bin / sh
mkdir -p /etc/docker/certs.d && cp /var/lib/boot2docker/certs/*.pem/etc/docker/certs.d

docker-machine restart default

Result was positive.

Another test was to modify the conf.json file in the path C:\Users\.docker\machine\machines\default\conf.json in the lines:

"CertDir": "C:\\Users\\cpd\\.Docker\\machine\\certs",
"CaCertPath": "C:\\Users\\cpd\\.Docker\\machine\\certs\\CA-SQUID.pem",
"CaPrivateKeyPath": "C:\\Users\\cpd\\.Docker\\machine\\certs\\ CA-SQUID_key.pem",

It turned out positive in running the Docker Quickstart Terminal.

But kitematic is still a mystery where I can insert the CA into it. Any solution?

**Comment by hannylicious** [comment]
@FrenchBen - is this something that can be reviewed? I'm yet another user who also needs the ability to specify their own CA file because our company performs a MITM with all traffic.

I'm in the same situation as @dclar43 - all traffic is unencrypted (and reencrypted before going outside) with a self-signed certificate.

Without the ability to specify our own ca-file, we're stuck with the 'self-signed certificate in chain' error... which seriously limits this tools usability.
