### ISSUE TITLE
Any Docker image install fails after latest docker update in windows 10

### ISSUE THREAD

**Issue by Jeager2** [docker/kitematic#3401]
### Expected behavior
Install WekanTeam Wekan using Kitematic UI

### Actual behavior
(HTTP code 500) server error - {"message":"Get https://registry-1.docker.io/v2/wekanteam/wekan/manifests/latest: unauthorized: incorrect username or password"}

### Information about the Issue
Windows 10 Professional [Version 10.0.16299.98]
Docker: Version 17.09.1-ce-win42 (14687)

docker-compose up also causes a similar error

PS C:\RemoteGIT\wekan-mongodb> docker-compose up
Creating network "wekanmongodb_wekan-tier" with driver "bridge"
Creating volume "wekanmongodb_wekan-db" with local driver
Creating volume "wekanmongodb_wekan-db-dump" with local driver
Pulling wekandb (mongo:3.2.18)...
ERROR: Get https://registry-1.docker.io/v2/library/mongo/manifests/3.2.18: unauthorized: incorrect username or password
PS C:\RemoteGIT\wekan-mongodb>

### Steps to reproduce the behavior

  1. docker-compose up

**Comment by mhelmetag** [comment]
This shouldn't have anything to do with the latest docker update. You should just be able to logout and login using your docker hub username (not email). If you update to the newest kitematic, it won't allow you to use your email too (causes problems like the one you see now) so that could make things less confusing.

**Comment by FrenchBen** [comment]
Please try to login using your Docker ID (hub username) instead of your email. This should fix the issue.
