### ISSUE TITLE
Images pulled using Docker CLI throw 404 in Kitematic when creating container

### ISSUE THREAD

**Issue by leosco** [docker/kitematic#3549]
### Expected behavior
Per https://github.com/docker/kitematic/issues/2870 I should be able to create containers using images I pulled using the CLI.
### Actual behavior
(HTTP code 404) no such image - no such image: docker.elastic.co/elasticsearch:6.1.3
### Steps to reproduce the behavior
On Kitematic latest on Mac, 
  1. `docker pull docker.elastic.co/elasticsearch/elasticsearch:6.1.3`
  2. In Kitematic, go to My Images and click Create on elasticsearch:6.1.3

This is very severe, as you lose Kitematic functionality with any image you pulled outside the GUI, such as anything not on Docker Hub, since that's the only thing you have to choose from right now...

I also want to point out that to view images pulled using the CLI, you need to restart Kitematic, which shouldn't be the default behavior.

**Comment by FrenchBen** [comment]
Pulling from the CLI to replicate an issue in Kitematic, means that you should be fair and pull from the same source. 

The image of `docker.elastic.co/elasticsearch/elasticsearch:6.1.3` is pulling from the repo of `docker.elastic.co` and not Docker's own repo (hub.docker.com).
Looking on hub, Elastic decided to deprecate their hub maintenance:
https://hub.docker.com/_/elasticsearch/

I'm not sure why they did that, but I would open a ticket with them to explain how annoying it is that they can't do a simple `docker push` to docker's hub.

**Comment by leosco** [comment]
So? I don't understand why the source of the image matters for it to work properly in Kitematic. Are you saying that Kitematic is designed to only work on images that are hosted on Docker Hub? I understand that Elastic deprecated their images on Docker and moved them to their own domain. Why should where the images were downloaded from matter for Kitematic to be useful?

That doesn't make sense, if you've already pulled the image into Docker, why should Kitematic throw a  404 when creating the container using the GUI? The image is already downloaded on the local storage. If I create the container using the CLI, I can still use it in the GUI, so clearly the issue is with how Kitematic creating the container.

See below, if I create the containers using the terminal, they appear in the GUI
<img width="512" alt="image" src="https://user-images.githubusercontent.com/11724770/35820927-432e40e4-0a75-11e8-92f8-b21e970b31af.png">

It's only when I attempt to create them using the GUI, that I get a 404 error. There obviously an issue here, not sure why you closed it...

**Comment by FrenchBen** [comment]
`Kitematic is designed to only work on images that are hosted on Docker Hub` that's correct - Kitematic is a Docker product, made to work with Docker's registry. 
The image you downloaded via the Elastic registry doesn't have the same namespace as the one downloaded from Hub. This it doesn't actually spin up the same image, and (hypothetical) it's possible that the hub image is intentionally not working, thus forcing the user to lookup where to properly download it.

**Comment by leosco** [comment]
That's exactly what it's doing then. You're hard-coding Kitematic to break unless the image was sourced directly from Docker Hub. If it's not you @FrenchBen I'd love if you could point me to the right person to talk about this. 

Why bother making an open source GUI for Docker if you're going to build in trivial proprietary roadblocks?

**Comment by FrenchBen** [comment]
It's not hard-coded to break for anything, it just happens that the image has different requirements. You see the same error by running it via the CLI `docker run elasticsearch`

**Comment by leosco** [comment]
I don't have that error. I run my images from https://www.docker.elastic.co/ just fine.

The name of the image in the local Docker store isn't just `elasticsearch`. You have to do `docker run docker.elastic.co/elasticsearch/elasticsearch:6.1.3`.

If you run `docker image ls`, it will show you the proper image names to use:
```terminal
docker image ls -a
REPOSITORY                                      TAG                 IMAGE ID            CREATED             SIZE
docker.elastic.co/kibana/kibana                 6.1.3               a3f439b54fc4        9 days ago          963MB
docker.elastic.co/elasticsearch/elasticsearch   6.1.3               abeec10402ff        9 days ago          556MB
```

Perhaps that's why Kitematic is throwing a 404, it's not using the right image name?

**Comment by FrenchBen** [comment]
I understand that pulling the latest image from the registry that Elastic built, will give you a working image. 
We're not responsible for keeping the images that are on Hub up to date, thus its at the discretion of the company to do so.

Doing a `docker pull elasticsearch` will pull a completely different image than what you've listed and the root cause of your problem:
`elasticsearch             latest              60ce0d08d205        2 weeks ago         581MB`

Docker store is a different storage, as it's pushing for container images that have been certified, hence the location of the image will be what the company chose. 

Kitematic uses the community based images, which may or may not work as expected.

**Comment by leosco** [comment]
I completely understand that. 

What I'm concerned about is that, using the CLI, I can download an image from any source, like https://www.docker.elastic.co/ and use it with the full functionality of Docker available to me. I'm not limited to only images from Docker Hub.

Then when I try to do the exact same thing in Kitematic, which is a GUI for Docker, and you would reasonably assume it has the same functionality, it doesn't work. You just told me it only is designed to work with images from Docker Hub.

That must be an issue, or if it is the intended behavior, then I disagree with it.
Because is means that Kitematic would be artificially restricting features available to users that are *already available* to them in Docker CLI.

**Comment by leosco** [comment]
Docker doesn't *only* work with images from Docker Hub, does it?

So why does Kitematic have that restriction, be it intentionally or not?

**Comment by Dylanlan** [comment]
I'm also experiencing this behaviour trying to upgrade to elastic search 6.x

After doing `docker pull docker.elastic.co/elasticsearch/elasticsearch:6.2.1`
I can see the 6.2.1 image in My Images, but clicking Create results in the 404 error

I noticed the error message says:
`(HTTP code 404) no such image - no such image: docker.elastic.co/elasticsearch:6.2.1: No such image: docker.elastic.co/elasticsearch:6.2.1`
which seems to suggest it's looking for `docker.elastic.co/elasticsearch:6.2.1` instead of `docker.elastic.co/elasticsearch/elasticsearch:6.2.1`

It seems strange to me if this is expected behaviour,
that it allows downloading of images from other than Docker Hub, and displays them, but doesn't allow creation of containers from them.

**Comment by leosco** [comment]
^^^^^^ my point exactly
