### ISSUE TITLE
Problem installing a container

### ISSUE THREAD

**Issue by mrtargaryen** [docker/kitematic#3912]
### Expected behavior

For Portainer to function

### Actual behavior

I receive this [Error Message](https://i.imgur.com/h2n8rMA.pngl) when attempting to create an account in Portainer. 

### Information about the Issue
I have been told by a user on GitHub that I need to "bind mount when creating Portainer from Kitematic" and I'm unaware of how to do that. I searched on searx.me  (meta search engine) for a guide but have been unable to find something.

Could someone point me in the right direction, if they have the time?

Thank you very much :-)

**Comment by mrtargaryen** [comment]
I ditched Kitematic and ran and pull the image into docker then ran $ docker run -d -p 9000:9000 --name portainer --restart always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer

And its working fine.

**Comment by iNamik** [comment]
I ran into this same issue today when trying out portainer.

Although I was also able to run the command line entry to create the image, I think there's a general question here worth exploring:

How do you use kitematic to mount `/var/run/docker.sock` into a mount point ?

The UI for mounting a volume doesn't let you select `docker.sock` since its not a folder.

Is there a way to do this within kitematic ?
