### ISSUE TITLE
Feature request - Better handling of containers / images that require configuring to function

### ISSUE THREAD

**Issue by arthurnn** [docker/kitematic#450]
Was given a shot at kitematic, and wanted to install locally a discourse image. however I got the following error https://www.dropbox.com/s/27qnx2ypaa4w1i4/Screenshot%202015-04-28%2014.20.25.png?dl=0 
not sure where I can get logs to facilitate the debugging process. Let me know if I can help with more information.

**Comment by zachberger** [comment]
Same error when trying to pull base/archlinux

**Comment by mchiang0610** [comment]
@arthurnn This problem is due to the discourse image requiring you to set some settings. You can follow their tutorial by using the whale button within Kitematic. 

@zachberger Creating a container from a base image in Kitematic will throw error as Kitematic doesn't know how to handle base images. 

We should have better error handing in both cases. 

- https://github.com/kitematic/kitematic/issues/485 Issue for discussing better error handling for base images in Kitematic 

Changing this one to be a feature request for better handling of containers requiring configuration.

**Comment by FrenchBen** [comment]
I believe most of these to be fixed in the latest Docker for Mac/Windows+Kitematic, with additional links to the docs
