### ISSUE TITLE
Failed to pull mussel docker image

### ISSUE THREAD

**Issue by teeto11** [docker/kitematic#5755]
it displays 
(HTTP code 404) no such image - no such image: microsoft/mssql-server-linux:latest: No such image: microsoft/mssql-server-linux:latest
<img width="1141" alt="Screenshot 2020-09-07 at 23 25 48" src="https://user-images.githubusercontent.com/31455698/92418813-7d07b400-f161-11ea-93a7-3a919b456bea.png">

**Comment by thaJeztah** [comment]
I think the old images should still be there, but that image is deprecated, and moved from https://hub.docker.com/r/microsoft/mssql-server-linux to `mcr.microsoft.com/mssql/server:xxxxxx`;l see https://hub.docker.com/_/microsoft-mssql-server

<img width="874" alt="Screenshot 2020-09-15 at 16 18 11" src="https://user-images.githubusercontent.com/1804568/93222299-1c830300-f76f-11ea-8fe0-cc3acdd81994.png">


closing this ticket because of the above, but feel free to continue the conversation.
