### ISSUE TITLE
[win alpha] kitematic tries to install VirtualBox, in a Hyper-V enabled System

### ISSUE THREAD

**Issue by pmario** [docker/kitematic#673]
System used: 
 - win 8.1 pro ... hyper-v enabled

Just started: `KitematicSetup-0.7.0.exe`
It starts to download VirtualBox. .... I did kill the program. 

 - It's not possible to run VB and Hyper-V at the same time. 

 - docker-machine already knows, how to use hyper-v, so kitematic can use the same code / mechanism. 

expected behaviour. 

- kitematic needs to check, if any hypervisor is already active. There may be several. 
- Even if eg: hyper-v is not active at the moment, it may be activated at the pc boot time with a boot-profile
   - see: http://www.hanselman.com/blog/SwitchEasilyBetweenVirtualBoxAndHyperVWithABCDEditBootEntryInWindows81.aspx
   - that's the mechanism I use atm. 
- So IMO there should be a user interaction, that asks the user, what should happen. 
  - install VB and tell the user, that it can't run at the same time as hyper-v if on win-pro or higher.
  - reboot and / or activate a hypervisor that is capable to run boot2docker.

**Comment by mchiang0610** [comment]
@pmario Really appreciate the feedback on this. No promises on Hyper-V support atm, especially during the alpha period. 

@jeffdm we should definitely add a check to detect Hyper-V is enabled (if they have it, hyper-v will always be on I believe unless you manually disable it). Only one hypervisor can run at a time.

**Comment by pmsousa** [comment]
Hi,

I have the exact same problem. My laptop has Hyper-V with several VM's due to other projects and also one with Boot2Docker in order to do some testing and demos with Docker Hub. And it works fine! At this moment, for me, uploading my Hyper-V Vm's to Azure and replacing Hyper-V for VirtualBox it's not an option...

I was about to test Kitematic because I saw the DockerCon livefeed and it seemed really cool but got stuck due to the VirtualBox install... I understand that at this moment it might be difficult to enable the setup to detect other already installed hypervisor but at least there could be a setup flag (command line flag) that we could use in order to skip the VirtualBox detection and installation.

Docker and Microsoft are building a very strong partnership and this Summer it's expected lots of new developments on that area. You should really consider this issue because it's a definitely show-stopper for lots of people.

**Comment by pmario** [comment]
>@jeffdm we should definitely add a check to detect Hyper-V is enabled (if they have it, hyper-v will always be on I believe unless you manually disable it). Only one hypervisor can run at a time. What do you think? Will this work?

IMO it also has to work if Hyper-V is installed and manually disabled, because it may be enabled at any time. So VB may brick the system. ... I personally don't want any software, to automatically install 3rd party software, without me acknowledging it. (I always have a look at the "advanced install" option, even if I click the "easy install" button afterwards ;)

**Comment by pmario** [comment]
A possibility (hack) to get it going: http://agup.tech/2015/08/14/hacking-at-kitematic-with-hyper-v-on-windows-10/  until PR Added ability to work with Hyper-v #1491  gets merged.

**Comment by FrenchBen** [comment]
@pmario Out of curiosity, what is the difference between your code and https://github.com/docker/kitematic/pull/1491 ?

**Comment by pmario** [comment]
Hi @FrenchBen. That's not my code. It's a story told by Anurag Gupta and I posted it here, as an info for others and me, how one could hack together a working windows app for hyper-v users.  ... 

#1491 is a better solution, but also has some hardcoded stuff. eg: The virtual network driver name, .. 

Imo #777 "Proposal: Add support for multiple machines", imo would be a better option but may be the slowest one to implement. Except all the resources are thrown together and the issues are resurrected. 

------------- (rant - OT kind of)

I'm having a look at Kitematic from time to time (every 2 month) and need to stop here.

![docker-toolbox-install-dealbreaker](https://cloud.githubusercontent.com/assets/374655/13538982/c9b6453c-e24d-11e5-9e21-db4c9d85806f.gif)

since I can't disable VBox installation, I need to stop the install process!

This behaviour breaks the whole Toolbox for me. I'd like to use a windows installer, for the docker related stuff, but I simply can't, without unwanted side effects. 

For me it seems hyper-v is a technology, you better don't bet on. Toolbox defs seem to be happy with iMacs and MS has enough to do, to catch up with the technology in general. ---- (end of rant)

**Comment by FrenchBen** [comment]
@pmario You can actually download the components individually if the Toolbox isn't doing it for you - Each of them above components have a github release area.

Toolbox bundles all of the items for you and makes Virtualbox a requirement since 'machine management' isn't available yet and thus becomes a _hard_ requirement to have the proper version of Virtualbox installed.

I agree that the hard-coding of the different interface for the HyperV patch isn't ideal, I may discuss it with the PR owner once I get a bit of time to go over all of the steps and possible enhancements. 
Thanks for the feedback!

**Comment by floradu88** [comment]
@pmario  @FrenchBen I look forward in forking the repository in order to change the install process(to be able to install docker without vbox), but for now I wanted to create a way so that you can use docker with hyper-v. I know I did some hardcoding, but I haven't find a way to create a virtual switch from command line yet to drop the hardcoding. Please do let me know the repository. Looking forward to make this available out of the box with hyper-v. 

Any other feedback would be very welcome.

Regards,
Radu

**Comment by pmario** [comment]
I'm about to install dev dependencies to build Kitematic. ... slow internet :)

@floradu88 

>I know I did some hardcoding, but I haven't find a way to create a virtual switch from command line yet to drop the hardcoding.

Have a look here:  https://blogs.technet.microsoft.com/heyscriptingguy/2013/10/09/use-powershell-to-create-virtual-switches/

There are commands to look up existing vswitches eg:  `Get-VMSwitch -SwitchType External` .. IMO we need internet access in order to pull images from docker hub. ...

If VMSwitches exist: `Get-VMSwitch` will get them. ... So there seem to be plenty of options to list and use existing ones. ... creating new ones seems to be simple too. As a user I would want, that the install process lets me choose the name. (but there should be a sensible default, to just hit enter :)

**Comment by FrenchBen** [comment]
I believe most of these to be fixed in the latest Docker for Mac/Windows+Kitematic.

**Comment by Wolvverine** [comment]
two years , and problem exist on win 8.1 pro with hyper-v enabled.
